# Generated by Django 5.1.3 on 2024-11-14 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_latitude', models.FloatField()),
                ('current_longitude', models.FloatField()),
                ('status', models.CharField(choices=[('flying', 'Flying'), ('landed', 'Landed')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField()),
                ('drone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='drone_app.drone')),
            ],
        ),
    ]
