# Generated by Django 5.1.3 on 2024-11-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
