# Generated by Django 5.1.3 on 2024-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drone_app', '0003_alter_drone_current_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drone',
            name='current_latitude',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='current_longitude',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='model',
        ),
        migrations.RemoveField(
            model_name='drone',
            name='status',
        ),
        migrations.AddField(
            model_name='drone',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='drone',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='Waypoint',
        ),
    ]
